use_local_db: true
local_db_path: "Tutorials/sandbox.db"

use_remote_db: false
remote_db_type: "sqlite"
remote_db_host: "example.com"
remote_db_port: 3306
remote_db_name: "your_database_name"
remote_db_user: "your_username"
remote_db_password: "your_password"

use_ssh_tunnel: false
ssh_host: "ssh.example.com"
ssh_port: 22
ssh_user: "ssh_username"
ssh_private_key_path: "/path/to/your/private/key"
ssh_password: ""  # Use this if not using a private key

max_connections: 5
connection_timeout: 30

enable_foreign_keys: true
journal_mode: "WAL"

db_structures:
  tables:
    - name: records
      columns:
        id: INTEGER PRIMARY KEY AUTOINCREMENT
        concept_recid: INTEGER NOT NULL
        concept_doi: TEXT
        type: TEXT
        title: TEXT NOT NULL
        subset: TEXT
        recid: INTEGER NOT NULL
        doi: TEXT
        version: TEXT
        access_right: 
          type: TEXT NOT NULL
          check: 
            - open
            - embargoed
            - restricted
            - closed
        license: TEXT
        owner_id: TEXT
        all_recids: TEXT
        changelogs: JSON
        modified: DATETIME
        created_at: DATETIME DEFAULT CURRENT_TIMESTAMP
        updated_at: DATETIME DEFAULT CURRENT_TIMESTAMP
      constraints:
        - UNIQUE (concept_recid, recid)
      indexes:
        - concept_recid
        - recid
        - doi
        - title

    - name: links
      columns:
        concept_recid: INTEGER NOT NULL
        recid: INTEGER NOT NULL
        self: TEXT
        html: TEXT
        doi: TEXT
        files: TEXT
        bucket: TEXT
        publish: TEXT
        edit: TEXT
        discard: TEXT
        new_version: TEXT
        updated_at: DATETIME DEFAULT CURRENT_TIMESTAMP
      primary_key:
        - concept_recid
        - recid
      foreign_keys:
        - columns: 
            - concept_recid
            - recid
          references:
            table: records
            columns:
              - concept_recid
              - recid
      indexes:
        - concept_recid
        - recid

    - name: mainfiles
      columns:
        concept_recid: INTEGER NOT NULL
        recid: INTEGER NOT NULL
        filetype: TEXT
        filename: TEXT NOT NULL
        direct_link: TEXT
        file_source: TEXT
        updated_at: DATETIME DEFAULT CURRENT_TIMESTAMP
      primary_key:
        - concept_recid
        - filename
      foreign_keys:
        - columns: 
            - concept_recid
            - recid
          references:
            table: records
            columns:
              - concept_recid
              - recid
      indexes:
        - concept_recid
        - recid
        - filename

    - name: states
      columns:
        concept_recid: INTEGER NOT NULL
        recid: INTEGER NOT NULL
        thumbnails_available: BOOLEAN
        edm_available: BOOLEAN
        metsmods_available: BOOLEAN
        updated_at: DATETIME DEFAULT CURRENT_TIMESTAMP
      primary_key:
        - concept_recid
        - recid
      foreign_keys:
        - columns: 
            - concept_recid
            - recid
          references:
            table: records
            columns:
              - concept_recid
              - recid
      indexes:
        - concept_recid
        - recid

    - name: thumbnails
      columns:
        concept_recid: INTEGER NOT NULL
        recid: INTEGER NOT NULL
        perspective: TEXT
        res_1000x1000: TEXT
        res_512x512: TEXT
        res_256x256: TEXT
        res_128x128: TEXT
        updated_at: DATETIME DEFAULT CURRENT_TIMESTAMP
      primary_key:
        - concept_recid
        - recid
        - perspective
      foreign_keys:
        - columns: 
            - concept_recid
            - recid
          references:
            table: records
            columns:
              - concept_recid
              - recid
      indexes:
        - concept_recid
        - recid
        - perspective

    - name: responses
      columns:
        concept_recid: INTEGER NOT NULL
        recid: INTEGER NOT NULL
        data: JSON
        updated_at: DATETIME DEFAULT CURRENT_TIMESTAMP
      primary_key:
        - concept_recid
        - recid
      foreign_keys:
        - columns: 
            - concept_recid
            - recid
          references:
            table: records
            columns:
              - concept_recid
              - recid
      indexes:
        - concept_recid
        - recid

    - name: rate_limiter
      columns:
        timestamp: REAL NOT NULL
      primary_key:
        - timestamp
      indexes:
        - timestamp

    - name: operations
      columns:
        id: INTEGER PRIMARY KEY AUTOINCREMENT
        concept_recid: INTEGER NOT NULL
        recid: INTEGER NOT NULL
        doi: TEXT
        operation: TEXT NOT NULL
        status: TEXT NOT NULL
        links: JSON
        files: JSON
        initiated: DATETIME
        modified: DATETIME
      indexes:
        - concept_recid
        - recid