project_title: &projectTitle "Maeyaert_Aug-2024"
short_title: &shortTitle "maeyaert-aug24"


paths:
  input:
    excel: "Input/*projectTitle/debug.xlsx"
    images: "Input/*projectTitle/Images"

  output:
    edms: "Output/*projectTitle/EDMs"
    jsons: "Output/*projectTitle/*shortTitle_{now}.json"
    csvs: "Output/*projectTitle/kate_presentation_{now}.csv"
    failed: "Output/failed_kate_presentation{now}.csv"
    resized_images: "Output/*projectTitle/Images/Resized"


logging:
  now_dateformat: "%Y-%b-%d_%Hh%Mm%Ss"
  level: INFO
  log_file_pattern: "Logs/*projectTitle/*shortTitle_{now}.log"
  log_format: "%(asctime)s - %(levelname)s - %(message)s"
  published_msg: "Published Entry {entry_counter} | DOI: {published_doi} | Data: {published_data}"


settings:
  use_env_api_key: true
  use_sandbox: true
  zenodo_api_key: ""
  zenodo_sandbox_api_key: ""
  rates_per_minute: 90
  rates_per_hour: 4750

  retrieve_coordinates: false

  split_authors: false
  split_description: true
  split_keywords: true

  add_image_metadata_to_description: true
  add_exif_to_description: true
  add_space_after_colon_in_author: true
  remove_copyright_symbol: true
  remove_mail_from_copyright: true

  upload_metadata_json: true
  upload_resized_image: true
  upload_resized_image_only: false

  image_resize:
    active: true
    ratio: 1.0
    use_ratio: false
    max_dimension_value: 256


person_masker:
  active: false
  bbox_model: "Models/yolov10x.pt"
  bbox_device: "cpu" # cpu | cuda
  segmentation_model: "Models/sam2_t.pt"
  segmentation_device: "cpu"
  threshold: 0.1
  max_files: -1 # set -1 to process all files

  blur_blackwhite: False # if False, B/W-Images will not be affected
  write_bbox_images: true
  write_segmented_images: true
  delete_bbox_after_upload: true
  delete_segmented_after_upload: false

  paths:
    input_images: "Input/*projectTitle/Images"
    bbox_images: "Output/*projectTitle/Images/TMP/bboxes"
    segmented_images: "Output/*projectTitle/Images/TMP/segmented"
    masked_images: "Output/*projectTitle/Images/persons_masked"
    processing_log: "Output/*projectTitle/Logs/persons_masked"

  process_extensions:
    - '.png'
    - '.jpg'
    - '.jpeg'
    - '.bmp'
    - '.gif'
    - '.tif'
    - '.tiff'
  

title_constructor:
  pos_0: "filename"
  pos_1: "description"
  separator: "-"


description_constructor:
  line_0: "<u>File Name</u>: {filename} <br>"
  line_1: "<u>Sublocation</u>: {sublocation} <br>"
  line_2: "<u>Location</u>: {location} <br>"
  line_3: "<u>Province</u>: {province} <br>"
  line_4: "<u>Country</u>: {country} <br>"
  line_5: "<u>Header</u>: {header} <br>"
  line_6: "<u>Description</u>: {description} <br>"
  line_7: "<u>Keywords</u>: {keywords} <br><br>"
  line_8: "<u>Author</u>: {author} <br>"
  line_9: "<u>Copyright</u>: {copyright} <br>"
  line_10: "<u>Rightholder's Mail</u>: {author_email} <br>"


geolocator:
  user_agent: "CoordsGetter/0.1 (mail@email.com)"
  timeout: 2
  sleep_time: 1
  max_attempts: 5
  backoff_factor: 1.5
  detailed_structured_query: false # adds state & province/county to the query (not recommended due to inconsistencies)
  reducer_split_by_hyphens: true # splits words by hyphens before reducing strings


column_mapping:
  filename: "file name"
  sublocation: "Sublocation"
  location: "location"
  province: "province"
  country: "country"
  header: "header"
  description: "description"
  author: "author"
  author_email: "author, email adress"
  copyright: "copyright information"
  keywords: "keywords"


zenodo_metadata:
  upload_type: "image"
  image_type: "photo"
  access_right: "open"
  license: "cc-by-4.0"
  creators:
    - name: "Paul M. R. Maeyaert"
  contributors:
    - name: "Paul M. R. Maeyaert"
      type: "RightsHolder"
  imprint_publisher: "Zenodo"
  initial_version: "0.0.1"


misc:
  capitalize_author_substrings: # array|false: capitalizes first letter of these items if they occur in author string
    - "photo: "
    - "source: "
    - "photography: "

  image_extensions:
    - ".jpg"

  split_characters:
    author:
      - ";"
    description:
      - ";"
      - "."
    keywords:
      - "|"
      - ";"

  split_exceptions:
    description:
      - "[A-Z]\\." # Single uppercase letter followed by a period (e.g., A., B., C.)
      - "\\d{1,2}\\." # One or two digits followed by a period (for centuries, e.g., 18., 19., 20.)
      - "etc."
      - "Inv." # Inventory
      - "Nr."
      - "Mr."
      - "Mrs."
      - "Ms."
      - "Mgr."
      # German Additions
      - "Jh." # Century (jahrhundert)
      - "z.B." # for example (zum Beispiel)
      - "d.h." # that is (das heißt)
      - "u.a." # among others (unter anderem)
      - "v.Chr." # before Christ
      - "n.Chr." # after Christ
      - "ca." # circa
      - "ggf." # if applicable (gegebenenfalls)
      - "inkl." # including
      - "exkl." # excluding
      - "bzw." # or rather (beziehungsweise)
      - "usw." # and so on (und so weiter)
      - "Dr." # Doctor
      - "Prof." # Professor
      - "St." # Saint
      - "Str." # Street (Straße)
      - "Bd." # Volume (Band)
      - "Tel." # Telephone
      - "Fa." # Company (Firma)
      - "Co." # Company
      - "AG." # Corporation (Aktiengesellschaft)
      - "e.V." # Registered association (eingetragener Verein)
      - "i.d.R." # usually (in der Regel)
      - "s.o." # see above (siehe oben)
      - "s.u." # see below (siehe unten)
      - "u.U." # under certain circumstances (unter Umständen)
      - "m.E." # in my opinion (meines Erachtens)
      - "z.T." # partly (zum Teil)
      - "u.v.m." # and much more (und vieles mehr)
      - "o.Ä." # or similar (oder Ähnliches)
      - "z.Zt." # at the moment (zur Zeit)
      - "o.g." # above-mentioned (oben genannt)
      - "u.g." # below-mentioned (unten genannt)
      # Spanish additions
      - "Sr." # Señor (Mr.)
      - "Sra." # Señora (Mrs.)
      - "Srta." # Señorita (Miss)
      - "Da." # Doña
      - "Lic." # Licenciado/a (Bachelor's degree holder)
      - "Ing." # Ingeniero/a (Engineer)
      - "Arq." # Arquitecto/a (Architect)
      - "Dra." # Doctora (Female Doctor)
      - "Profa." # Profesora (Female Professor)
      - "Gral." # General
      - "Cnel." # Coronel (Colonel)
      - "Tte." # Teniente (Lieutenant)
      - "Cap." # Capitán (Captain)
      - "Av." # Avenida (Avenue)
      - "Pza." # Plaza
      - "Calle." # Street
      - "núm." # número (number)
      - "tel." # teléfono (telephone)
      - "apdo." # apartado (P.O. Box)
      - "a.C." # antes de Cristo (B.C.)
      - "d.C." # después de Cristo (A.D.)
      - "p.ej." # por ejemplo (for example)
      - "Ud." # Usted (formal you)
      - "Uds." # Ustedes (formal you plural)
      - "S.A." # Sociedad Anónima (Corporation)
      - "S.L." # Sociedad Limitada (Limited Company)
      - "Cía." # Compañía (Company)
      # Italian additions
      - "Sig." # Signore (Mr.)
      - "Sig.ra" # Signora (Mrs.)
      - "Sig.na" # Signorina (Miss)
      - "Dott." # Dottore (Doctor)
      - "Dott.ssa" # Dottoressa (Female Doctor)
      - "Prof." # Professore (Professor)
      - "Prof.ssa" # Professoressa (Female Professor)
      - "Ing." # Ingegnere (Engineer)
      - "Arch." # Architetto (Architect)
      - "Avv." # Avvocato (Lawyer)
      - "Geom." # Geometra (Surveyor)
      - "Rag." # Ragioniere (Accountant)
      - "Gen." # Generale (General)
      - "Col." # Colonnello (Colonel)
      - "Cap." # Capitano (Captain)
      - "S.p.A." # Società per Azioni (Joint-stock company)
      - "S.r.l." # Società a responsabilità limitata (Limited liability company)
      - "p.zza" # piazza (square)
      - "tel." # telefono (telephone)
      - "ecc." # eccetera (et cetera)
      - "a.C." # avanti Cristo (B.C.)
      - "d.C." # dopo Cristo (A.D.)

      # French additions
      - "M." # Monsieur (Mr.)
      - "Mme" # Madame (Mrs.)
      - "Mlle" # Mademoiselle (Miss)
      - "Dr" # Docteur (Doctor)
      - "Pr" # Professeur (Professor)
      - "Me" # Maître (used for lawyers)
      - "Mgr" # Monseigneur (Monsignor)
      - "Gén." # Général (General)
      - "Col." # Colonel
      - "Cpt." # Capitaine (Captain)
      - "Lt." # Lieutenant
      - "St" # Saint
      - "Ste" # Sainte (female Saint)
      - "av." # avenue
      - "bd." # boulevard
      - "pl." # place (square)
      - "tél." # téléphone
      - "etc." # et cætera
      - "ex." # exemple (example)
      - "av. J.-C." # avant Jésus-Christ (B.C.)
      - "apr. J.-C." # après Jésus-Christ (A.D.)
      - "S.A." # Société Anonyme (Corporation)
      - "S.A.R.L." # Société à responsabilité limitée (Limited liability company)